<!--
Copyright © 2012, Chengbin WANG
All rights reserved. Not for commercial use
binbinaus@gmail.com

-->

<?php
//insert data generated by insert.php into sql

$con = mysql_connect("localhost","root","");
if (!$con)
  {
  die('Could not connect: ' . mysql_error());
  }

mysql_select_db("addressbook", $con);

$sql="INSERT INTO Persons (FirstName, LastName, Address, Email, Tel)
VALUES
('$_POST[firstname]','$_POST[lastname]','$_POST[address]', '$_POST[email]', '$_POST[tel]')";

if (!mysql_query($sql,$con))
  {
  die('Error: ' . mysql_error());
  }
echo "1 record added<br>";

mysql_close($con);

header("location: index.php");


?>
